upstream stock42_webapp {
    server 127.0.0.1:3000;
    keepalive 32;
}

upstream stock42_backoffice {
    server 127.0.0.1:3001;
    keepalive 32;
}

upstream stock42_api {
    server 127.0.0.1:4000;
    keepalive 64;
}
